import 'w3-css/w3.css';

import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>whale</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <header>
          <div>
            <p className="">nerd</p>
          </div>
        </header>

        <p>whale</p>
      </main>
    </div> 
  )
}
